/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    input cclk,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    input avr_tx,
    input avr_rx_busy,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [16-1:0] M_digits_digits;
  reg [14-1:0] M_digits_value;
  bin_to_dec_1 digits (
    .value(M_digits_value),
    .digits(M_digits_digits)
  );
  
  wire [1-1:0] M_start_stop_button_out;
  reg [1-1:0] M_start_stop_button_in;
  button_conditioner_2 start_stop_button (
    .clk(clk),
    .in(M_start_stop_button_in),
    .out(M_start_stop_button_out)
  );
  wire [1-1:0] M_reset_button_out;
  reg [1-1:0] M_reset_button_in;
  button_conditioner_2 reset_button (
    .clk(clk),
    .in(M_reset_button_in),
    .out(M_reset_button_out)
  );
  wire [14-1:0] M_stopwatch_value;
  reg [1-1:0] M_stopwatch_rst;
  reg [1-1:0] M_stopwatch_start_stop;
  stopwatch_4 stopwatch (
    .clk(clk),
    .rst(M_stopwatch_rst),
    .start_stop(M_stopwatch_start_stop),
    .value(M_stopwatch_value)
  );
  wire [1-1:0] M_edge_detector_out;
  reg [1-1:0] M_edge_detector_in;
  edge_detector_5 edge_detector (
    .clk(clk),
    .in(M_edge_detector_in),
    .out(M_edge_detector_out)
  );
  wire [8-1:0] M_seg_seg;
  wire [4-1:0] M_seg_sel;
  reg [16-1:0] M_seg_values;
  reg [4-1:0] M_seg_decimal;
  multi_seven_seg_6 seg (
    .clk(clk),
    .rst(rst),
    .values(M_seg_values),
    .decimal(M_seg_decimal),
    .seg(M_seg_seg),
    .sel(M_seg_sel)
  );
  wire [1-1:0] M_ctr_value;
  counter_7 ctr (
    .clk(clk),
    .rst(rst),
    .value(M_ctr_value)
  );
  
  always @* begin
    M_start_stop_button_in = io_button[1+0-:1];
    M_reset_button_in = io_button[3+0-:1];
    M_edge_detector_in = M_start_stop_button_out;
    M_stopwatch_start_stop = M_edge_detector_out;
    M_stopwatch_rst = M_reset_button_out;
    M_digits_value = M_stopwatch_value;
    M_seg_values = M_digits_digits;
    M_seg_decimal = 4'ha;
    io_seg = ~M_seg_seg;
    io_sel = ~M_seg_sel;
  end
endmodule
