/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     MAX_VALUE = 50000000/2
*/
module divBlinker_2 (
    input clk,
    input rst,
    input divi,
    output reg out
  );
  
  localparam MAX_VALUE = 26'h17d7840;
  
  
  reg [24:0] M_ctr_d, M_ctr_q = 1'h0;
  reg M_led_d, M_led_q = 1'h0;
  
  always @* begin
    M_led_d = M_led_q;
    M_ctr_d = M_ctr_q;
    
    M_ctr_d = M_ctr_q + 1'h1;
    if (M_ctr_q == 27'h17d783f) begin
      M_ctr_d = 1'h0;
      M_led_d = ~M_led_q;
    end
    out = M_led_q;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_ctr_q <= 1'h0;
      M_led_q <= 1'h0;
    end else begin
      M_ctr_q <= M_ctr_d;
      M_led_q <= M_led_d;
    end
  end
  
endmodule
