/*
   This file was generated automatically by the Mojo IDE version B1.3.5.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module convert_2 (
    input [23:0] value,
    output reg [23:0] better
  );
  
  
  
  always @* begin
    
    case (value)
      1'h1: begin
        better = 1'h0;
      end
      2'h2: begin
        better = 1'h1;
      end
      3'h4: begin
        better = 2'h2;
      end
      4'h8: begin
        better = 2'h3;
      end
      5'h10: begin
        better = 3'h4;
      end
      6'h20: begin
        better = 3'h5;
      end
      7'h40: begin
        better = 3'h6;
      end
      8'h80: begin
        better = 3'h7;
      end
      default: begin
        better = 1'h0;
      end
    endcase
  end
endmodule
